Shrink shyftgeth image size
ShyftNetwork/shyft_go-ethereum pull request #112
Opened 2018-10-08 17:23 UTC by larry-shyft

Using two-stage build to reduce shyftgeth image size on disk from 1.6 GB to 71 MB, for quicker build and pull from Docker Hub.

REPOSITORY                      TAG                 IMAGE ID            CREATED             SIZE
go-empyrean_shyftgeth           latest              d1db5e5c4db4        29 minutes ago      70.7MB
<none>                          <none>              46f103e69928        29 minutes ago      1.66GB

To connect to testnet:
 docker-compose -f docker-compose.production.yml up

2018-10-09 02:05 UTC, ChainSafe commented
@priom @dbkbali please review

2018-10-09 18:24 UTC, dbkbali requested changes
This looks good to me, we should document these changes in a) the Readme and b) the shyft_documentation folder which is used to generate these docs https://shyftnetwork.github.io/go-empyrean/ - both of these contain docker sections - you could keep it to a minimum - ie describe what these docker files generate in terms of a testnet node - ie. bootnode, non mining for testnet etc. Subject to the addition of this documentation I am onside with approving this. Great job at getting a reduction in image size..

2018-10-09 18:25 UTC, priom commented
@larry-shyft the 71mb size is for postgres only...shyftgeth is still over 2.8gb

2018-10-09 18:34 UTC, priom commented
@larry-shyft okay the production shyftgeth is 71mb..but it will always have an extra image 2.8gb size because of the multistage build..

2018-10-09 18:40 UTC, priom commented
@larry-shyft there are some more issues with the production docker, it doesnt seem to generate DAG and mine

2018-10-10 15:50 UTC, larry-shyft commented
@priom The intermediate image will be there to occupy 1.66GB, but only shyftgeth (70.7MB) will need to be pushed to and pulled from Docker Hub.

The --mining option is not there by default. One can do "miner.start()" in javaScript console, and node will start mining.

2018-10-10 15:52 UTC, GregTheGreek commented
@larry-shyft i have to disagree, we defintiely need the PG and API being pushed. WE could remove the UI if we wanted to

2018-10-10 17:23 UTC, larry-shyft commented
@GregTheGreek Yeah PG and API will be pushed. For those Dockerfiles, there are no differences between /development and /production

This PR is essentially just dealing with /docker/production/shyftGeth/Dockerfile

2018-10-11 18:58 UTC, priom commented
@larry-shyft this dockerfile should work for production servers, but it would be better to have the same in development with the default mining option (startShyftgeth.sh)

2018-10-15 18:36 UTC, GregTheGreek commented
@larry-shyft ok cool
@priom ,@dbkbali  - if its good merge.

2018-10-16 17:29 UTC, merged