Refactor of PG Connection/DB/TABLE Creation
ShyftNetwork/shyft_go-ethereum pull request #73
Opened 2018-09-07 02:37 UTC by dbkbali

Refactor - ensures connection pooling is optimized

2018-09-07 05:58 UTC, dutterbutter reviewed
Very happy we no longer are passing sqldb around everywhere. I was able to run this branch in docker with no issue. My only question/suggestion is in genesis.go LN 225 regarding the if !exist, shouldn't we be handling an error there? Such as if exist {}?

2018-09-07 13:12 UTC, dbkbali commented
@dutterbutter - The signature of block exists (LN 331 core/shyft_database_util.go) has been changed to return only a boolean - with error handling handled in BlockExists - ie. so in the event an error is returned when executing the db query it will  panic at line 340- BlockExists, which matches previous behavior except rather than triggering the panic in genesis.go by returning the full response for assessment of true, false or an error - genesis.go only has to deal with the true false scenario if there is no error.

2018-09-07 18:09 UTC, GregTheGreek commented on core/db.go
> +}
do we want to panic?

2018-09-07 18:11 UTC, GregTheGreek commented on core/shyft_database_util.go
>  	sqlExistsStatement := `SELECT isContract from txs WHERE to_addr=($1)`
add `;` end of query

2018-09-07 18:11 UTC, GregTheGreek commented on core/shyft_database_util.go
>  	updateSQLStatement := `UPDATE accounts SET balance = ($2), accountNonce = ($3) WHERE addr = ($1)`
here as well

2018-09-07 18:12 UTC, GregTheGreek requested changes
Just a few changes, add `;` on sql statements to remain consistent and potential panic. See comments.

2018-09-08 13:54 UTC, GregTheGreek approved these changes

2018-09-08 13:55 UTC, merged